apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: movies-secret
  labels:
    app: movies
stringData:
  API_TOKEN: $API_TOKEN
  API_KEY: $API_KEY
  SECRET_KEY: $SECRET_KEY
  ALGORITHM: $ALGORITHM
  DATABASE_URL: $DATABASE_URL